### ISSUE TITLE
Ajustes no projeto

### ISSUE THREAD

**Issue by oliveiralex** [vilsonmoro/github-user-search#1]
Olá vilsonmoro,

Seu trabalho foi aceito, parabéns! Porém para ficar 100% é necessário fazer um pequeno ajuste.
Ao apresentar a tela de busca (rota: /search)  está sendo exibida a div com as informações do usuário, neste caso vazias pois a requisição ainda não foi realizada. O mais adequado seria esconde-la até que a busca seja feita, conforme o exemplo do figma.

Por favor, faça os ajustes assim que possível.

Atenciosamente,

**Comment by vilsonmoro** [comment]
Olá, alteração realizada e atualizada no git

obrigado pelo feedback,

abraço

Em sex., 12 de fev. de 2021 às 17:20, Alexandre <notifications@github.com>
escreveu:

**Comment by oliveiralex** [comment]
Parabéns vilsonmoro! Obrigado pelos ajustes!

Abraço
